### ISSUE TITLE
Cannot submitTransaction in application

### ISSUE THREAD

**Issue by lichen-liu** [lichen-liu/ark2#2]
In application, App.java:invokePeer()

With this line:
```Java
System.out.println("\n[1] result: " + new String(contract.submitTransaction("initLedger")));
```

Seeing following error.
```
log4j:WARN No appenders could be found for logger (org.hyperledger.fabric_ca.sdk.helper.Config).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Successfully enrolled user "admin" and imported it into the wallet
An error occurred when registrating user
org.hyperledger.fabric_ca.sdk.exception.RegistrationException: Error while registering the user app.App$1@327120c8 url: https://localhost:7054  POST request to https://localhost:7054 failed request body {"id":"appUser3","type":"client","affiliation":"org1.department1","attrs":[]}. Response: {"result":"","errors":[{"code":0,"message":"Registration of 'appUser3' failed: Identity 'appUser3' is already registered"}
],"messages":[],"success":false}

[0] result: {"reference":"ref","incomingTransactionElement":{"pointAmount":100,"userId":"user0"},"signature":"sig","outgoingTransactionElements":[{"pointAmount":50,"userId":"user1"},{"pointAmount":50,"userId":"user2"}],"timestamp":"now"}
org.hyperledger.fabric.gateway.ContractException: No valid proposal responses received. 2 peer error responses: Channel Channel{id: 1, name: mychannel} Sending proposal with transaction: 62d649165b8b2fec85fac44e30428bc9e30289811f9ef3d5cc0c1c1ff5a5b6ce to Peer{ id: 7, name: peer0.org2.example.com:9051, channelName: mychannel, url: grpcs://peer0.org2.example.com:9051, mspid: Org2MSP} failed because of: gRPC failure=Status{code=UNAVAILABLE, description=Unable to resolve host peer0.org2.example.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: peer0.org2.example.com
        at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:420)
        at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:256)
        at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:213)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.UnknownHostException: peer0.org2.example.com
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
        at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:640)
        at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:388)
        ... 5 more
}; Channel Channel{id: 1, name: mychannel} Sending proposal with transaction: 62d649165b8b2fec85fac44e30428bc9e30289811f9ef3d5cc0c1c1ff5a5b6ce to Peer{ id: 5, name: peer0.org1.example.com:7051, channelName: mychannel, url: grpcs://peer0.org1.example.com:7051, mspid: Org1MSP} failed because of: gRPC failure=Status{code=UNAVAILABLE, description=Unable to resolve host peer0.org1.example.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: peer0.org1.example.com
        at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:420)
        at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:256)
        at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:213)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.UnknownHostException: peer0.org1.example.com
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
        at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:640)
        at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:388)
        ... 5 more
}
        at org.hyperledger.fabric.gateway.impl.TransactionImpl.validatePeerResponses(TransactionImpl.java:196)
        at org.hyperledger.fabric.gateway.impl.TransactionImpl.submit(TransactionImpl.java:93)
        at org.hyperledger.fabric.gateway.impl.ContractImpl.submitTransaction(ContractImpl.java:50)
        at app.App.invokePeer(App.java:75)
        at app.App.main(App.java:45)
```

**Comment by lichen-liu** [comment]
Fixed.
